version: '3.8'
services:
  blocky_dns:
    image: spx01/blocky
    networks:
      - ksp-proxy
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - TZ=Europe/Amsterdam
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
#        constraints:
#          - "node.role==manager"

networks:
  ksp-proxy:
    external: true